[settings]
timeout = 120

[relaychain]
chain = "rococo-local"

[[relaychain.nodes]]
name = "alice"
validator = true

[[relaychain.nodes]]
name = "bob"
validator = true

[[parachains]]
id = 1000
addToGenesis = true
cumulus_based = true
#chain_spec_path = "./chain_spec.json"

[[parachains.collators]]
name = "dave"
command = "./target/release/parachain-template-node"
ws_port = 9823
rpc_port = 8833
port = 30335
args = ["--collator","--dave","--offchain-worker always", "--enable-offchain-indexing true","--log offchain=trace,logger=trace"]

[[parachains.collators]]
name = "charlie"
command = "./target/release/parachain-template-node"
ws_port = 9822
rpc_port = 9946
port = 30336
args = ["--collator", "--charlie","--offchain-worker always", "--enable-offchain-indexing true","--log offchain=trace,logger=trace"]

[[parachains.collators]]
name = "eve"
command = "./target/release/parachain-template-node"
ws_port = 9836
rpc_port = 9944
args = ["--collator", "--eve","--offchain-worker always", "--enable-offchain-indexing true","--log offchain=trace,logger=trace"]



